version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  webapp:
    depends_on:
      - db
    image: appdbchallenge:latest
    restart: always
    ports:
      - '8080:3000'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    networks: 
      - appnet 
networks:
  appnet:
volumes:
  db_data: